# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MediaPlayerUIDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'libksygpulive/libksygpulive’
  pod 'SDWebImage'
  pod 'JSONModel'
  pod 'Masonry'
  pod 'Toast'
  pod 'Bugly'
  # Pods for MediaPlayerUIDemo

end
